---
title: "Day 1"
author: "Joshua Davidson"
date: "8/27/2019"
output: html_document
---

## Data Structures

### Vector

```{r}
v1 <- c("a", "b", "c", "d", "e", 
        "f", "g", "h", "i", "j")
```

```{r}
print(v1)
```

```{r}
v2 <- c(1:10)
```

```{r}
v3 <- c(TRUE, FALSE, TRUE, FALSE)
```

```{r}
class(v1)
class(v2)
class(v3)
```

```{r}
v4 <- c(-1.5,2.3, 4.7)
class(v4)
```

```{r}
class(v1)
```
[1]"character"

```{r}
v2 <- c(1:4)
```

```{r}
class(v2)
```

[1]"integer"
#### Naming a vector elements
```{r}
setNames(v2, v1)
```

#### Length of a vector
```{r}
length(v1)
```


#### Subsetting a vector

```{r}
print(v1[3])
```

```{r}
print(v1[c(1,3)])
```

```{r}
print(letters)
```

```{r}
print(letters)
```

```{r}
print(letters[c(1:10)])
```

can use negative sign to exclude
```{r}
print(letters[-c(1:10)])
```

### Factor

```{r}
attributes(v1)
```

```{r}
attributes(setNames(v2,v1))
```


#### Creating a factor

```{r}
f1 <- factor(v2)
```

```{r}
print(f1)
```

```{r}
attributes(f1)
```

```{r}
v4 <- c(1, 1, 1, 2, 2, 4, 3, 4, 3, 3)
```

```{r}
length(v4)
```

```{r}
f2 <- factor(v4)
```

```{r}
print(f2)
```

```{r}
table(f2)
```

```{r}
months <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
```

```{r}
months_fact <- factor(months, levels=c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"), ordered=TRUE)
```

```{r}
plot(table(months_fact))
```

```{r}
print(months_fact)
```

### Matrix

```{r}
matrix(v2, nrow =4, ncol = 1)
```

```{r}
matrix(v2, nrow =2, ncol = 2)
```

```{r}
matrix(v2, nrow =2, ncol = 2, byrow=TRUE)
```

```{r}
m1 <- matrix(v2, nrow =2, ncol = 2)
```

```{r}
print(m1[2,1])
```

```{r}
print(m1[,2])
```


### Data Frame
```{r}
d2 <- read.csv(file="dataset.csv", stringsAsFactors = FALSE)
```

```{r}
print(d2)
```


### List
```{r}
l1 <- list(vec1 = v1, myletters = letters, mynumbers = c(1:100), mydata =d2, mymatrix=m1)
```


```{r}
print(l1)
```

```{r}
l2 <- list(v1, letters,c(1:100),d2,m1)
```

```{r}
print(l2[2])
```

```{r}
print(l2[[2]])
```

```{r}
class(l2[2])
class(l2[[2]])
```

